spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5436}/ai_db
    username: ${DB_USER:ai_user}
    password: ${DB_PASSWORD:ai_pass}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:29092}
  ai:
    openai:
      api-key: ${GROQ_API_KEY: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}
    huggingface:
      api-key: ${HF_API_KEY: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}

server:
  port: ${SERVER_PORT:18085}